# Generated by Django 4.2.8 on 2026-01-28 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_api', '0002_timeslot_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='timezone',
            field=models.CharField(blank=True, default='America/Los_Angeles', max_length=50, null=True),
        ),
    ]
