# Generated by Django 4.2.8 on 2026-01-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_api', '0004_remove_timeslot_timezone_contact_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='is_active',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
