# Generated by Django 4.2.8 on 2026-01-29 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendar_api', '0006_timeslot_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='America/Los_Angeles', help_text='Timezone for displaying timeslots', max_length=50)),
                ('email_on_confirmation', models.BooleanField(default=True, help_text='Send email when a timeslot is confirmed')),
                ('email_on_cancellation', models.BooleanField(default=True, help_text='Send email when a timeslot is cancelled')),
                ('email_daily_summary', models.BooleanField(default=False, help_text='Send daily summary of timeslots')),
                ('items_per_page', models.IntegerField(default=10, help_text='Number of items to display per page')),
                ('dark_mode', models.BooleanField(default=True, help_text='Enable dark mode in the admin panel')),
                ('calendar_show_weekends', models.BooleanField(default=True, help_text='Show weekends in calendar view')),
                ('calendar_start_hour', models.IntegerField(default=10, help_text='Start hour for calendar (0-23)')),
                ('calendar_end_hour', models.IntegerField(default=18, help_text='End hour for calendar (0-23)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Settings',
                'verbose_name_plural': 'User Settings',
            },
        ),
    ]
