# Generated by Django 4.2.8 on 2026-02-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_api', '0007_settings'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
