# Generated by Django 4.2.8 on 2026-01-28 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='topic',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
