# Generated by Django 4.2.8 on 2026-01-28 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_api', '0003_alter_timeslot_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='timezone',
        ),
        migrations.AddField(
            model_name='contact',
            name='timezone',
            field=models.CharField(blank=True, default='America/Los_Angeles', max_length=50, null=True),
        ),
    ]
