# Generated by Django 4.2.8 on 2026-01-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_api', '0005_remove_timeslot_is_active_timeslot_is_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
