from django.contrib import admin
from ..models import Settings


@admin.register(Settings)
class SettingsAdmin(admin.ModelAdmin):
    """
    Admin interface configuration for Settings model.
    
    EXTENSION DETAILS:
    - Extends: django.contrib.admin.ModelAdmin (Django's base model admin class)
    - Model: calendar_api.models.Settings
    - Purpose: Customizes how user settings are displayed and edited in admin
    - Registration: Uses @admin.register(Settings) decorator instead of manual registration
    
    DECORATOR REGISTRATION:
    - @admin.register(Settings) automatically registers this admin with Django's default admin site
    - This is different from calendar_admin_site registration
    - If you want to use this in calendar_admin_site instead, you would:
      - Remove the @admin.register decorator
      - Add to calendar_api/admin/__init__.py: calendar_admin_site.register(Settings, SettingsAdmin)
    
    FEATURES CONFIGURED:
    
    1. LIST VIEW (displayed when browsing settings)
    2. SEARCH (find users' settings by username/email)
    3. READ-ONLY FIELDS (auto-generated timestamps)
    4. FIELDSETS (organize settings into logical groups)
    
    USAGE IN ADMIN:
    1. Navigate to /admin/calendar_api/settings/
    2. See list of user settings with timezone, notifications, preferences
    3. Use search bar to find specific users
    4. Click to edit a user's settings
    5. Settings are organized by category (Timezone, Notifications, etc.)
    """
    
    # LIST VIEW CONFIGURATION
    # Columns shown when browsing all settings
    # Shows user, timezone, dark_mode preference, email preferences, and last update time
    list_display = ('user', 'timezone', 'dark_mode', 'email_daily_summary', 'updated_at')
    
    # SEARCH FUNCTIONALITY
    # Users can search through user-related fields
    # Useful for admins to find specific user settings
    # Searches across user's username, email, first name, last name
    search_fields = ('user__username', 'user__email', 'user__first_name', 'user__last_name')
    
    # READ-ONLY FIELDS
    # These fields cannot be edited - auto-generated by Django
    # created_at: When the settings were first created
    # updated_at: When the settings were last modified
    readonly_fields = ('created_at', 'updated_at')
    
    # FIELDSETS ORGANIZATION
    # Groups related settings into collapsible sections
    # Makes the edit form easier to navigate for users with many options
    # Each fieldset is a tuple: (section_title, {'fields': (...), 'classes': (...)})
    fieldsets = (
        ('User', {
            # Which user these settings belong to
            'fields': ('user',)
        }),
        ('Timezone Settings', {
            # Time zone configuration for the user
            'fields': ('timezone',),
        }),
        ('Notification Preferences', {
            # Email notification settings
            # User can choose when to receive email notifications
            'fields': ('email_on_confirmation', 'email_on_cancellation', 'email_daily_summary'),
        }),
        ('Display Preferences', {
            # UI/UX settings
            # dark_mode: Toggle dark theme on/off
            # items_per_page: How many items to show per page in lists
            'fields': ('dark_mode', 'items_per_page'),
        }),
        ('Calendar Preferences', {
            # Calendar-specific display options
            # calendar_show_weekends: Include Saturday/Sunday in calendar view
            # calendar_start_hour: First hour to show (e.g., 8 AM)
            # calendar_end_hour: Last hour to show (e.g., 6 PM)
            'fields': ('calendar_show_weekends', 'calendar_start_hour', 'calendar_end_hour'),
        }),
        ('Metadata', {
            # System-generated timestamps
            'fields': ('created_at', 'updated_at'),
            'classes': ('collapse',)  # 'collapse' makes this section closeable/hidden by default
        }),
    )
